// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmgjatzisypbddvlfzbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZ2phdHppc3lwYmRkdmxmemJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDE0OTgsImV4cCI6MjA2OTgxNzQ5OH0.rIwBsKHJoGbxYH1MfapkMQkhCgVgzLlV4ZCAt-ki6yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});